name: GitHub Contexts
on: push
jobs:
  print:
    runs-on: ubuntu-24.04
    steps:
      - name: github.ref test
        if: github.ref == 'refs/heads/main'
        run: echo "${{ github.ref }}"  # refs/heads/main
