name: Manual type choise
on:
  workflow_dispatch:
    inputs:
      log-level:
        type: choice
        options:
          - info
          - warn
          - error
        description: Display drop-down menu
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.log-level }}"
