name: Ruby CI

on:
  push

jobs:
  rubocop:
    name: execution rubocop
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: execution rubocop
        run: bundle exec rubocop

  rspec:
    name: execution rspec
    runs-on: ubuntu-latest

    needs: [rubocop]

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: execution rspec
        run: bundle exec rspec
