name: Ruby CI

on:
  push

jobs:
  ruby_ci:
    name: ruby static analysis and testing

    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: execution rubocop
        run: bundle exec rubocop

      - name: execution rspec
        run: bundle exec rspec
